# Generated by Django 5.1.8 on 2025-04-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluginConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('plugin_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('SMS', 'SMS')], max_length=20)),
                ('module_path', models.CharField(help_text='Python module path (e.g., plugins.sms.twilio_plugin)', max_length=200)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configuration JSON (e.g., API keys)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
