# Generated by Django 5.1.8 on 2025-04-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginconfig',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration JSON (e.g., API keys)'),
        ),
        migrations.AlterField(
            model_name='pluginconfig',
            name='module_path',
            field=models.CharField(help_text='Python module path (e.g., plugins.sms.twilio_plugin)', max_length=200),
        ),
        migrations.AlterField(
            model_name='pluginconfig',
            name='plugin_type',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('SMS', 'SMS')], max_length=20),
        ),
    ]
