# Generated by Django 5.1.8 on 2025-04-19 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='static_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address'], name='customers_r_ip_addr_75bf84_idx')],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='router',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.router'),
        ),
    ]
