# Generated by Django 5.1.8 on 2025-04-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='redeemed_by',
        ),
        migrations.AddField(
            model_name='router',
            name='connection_type',
            field=models.CharField(choices=[('API', 'MikroTik API'), ('RADIUS', 'RADIUS Server'), ('VPN', 'VPN Tunnel')], default='API', max_length=20),
        ),
        migrations.AddField(
            model_name='router',
            name='radius_secret',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='router',
            name='radius_server',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='router',
            name='vpn_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='router',
            name='vpn_protocol',
            field=models.CharField(blank=True, choices=[('OPENVPN', 'OpenVPN'), ('PPTP', 'PPTP'), ('L2TP', 'L2TP')], max_length=20),
        ),
        migrations.AddField(
            model_name='router',
            name='vpn_server',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='router',
            name='vpn_username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voucher',
            name='prefix',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='router',
            name='api_port',
            field=models.IntegerField(blank=True, default=8728, null=True),
        ),
        migrations.AlterField(
            model_name='router',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='router',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='router',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
