# Generated by Django 5.1.8 on 2025-04-19 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_password_subscription_static_ip_router_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='package',
            name='customers_p_name_20ae00_idx',
        ),
        migrations.RenameField(
            model_name='sessionlog',
            old_name='data_usage',
            new_name='bytes_in',
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='bytes_out',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='connection_type',
            field=models.CharField(choices=[('PPPOE', 'PPPoE'), ('STATIC', 'Static'), ('HOTSPOT', 'Hotspot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.package'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='router',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.router'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['router'], name='customers_s_router__98b958_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['static_ip'], name='customers_s_static__3c9d8b_idx'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.subscription'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issued_date'], name='customers_i_issued__33fe8c_idx'),
        ),
    ]
