# Generated by Django 5.1.8 on 2025-04-19 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_invoice_remove_package_customers_p_name_20ae00_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='customers_s_created_e3a9ad_idx'), models.Index(fields=['is_read'], name='customers_s_is_read_bd5446_idx')],
            },
        ),
    ]
