# Generated by Django 5.1.8 on 2025-04-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='connection_type',
            field=models.CharField(choices=[('HOTSPOT', 'Hotspot'), ('PPPOE', 'PPPoE'), ('STATIC', 'Static'), ('VPN', 'VPN')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='duration_hours',
            field=models.IntegerField(blank=True, help_text='Hours for short-term plans (e.g., Hotspot)', null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='vpn_server',
            field=models.CharField(blank=True, help_text='VPN server address (e.g., for PPTP/L2TP)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration_days',
            field=models.IntegerField(blank=True, help_text='Days for long-term plans', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='connection_type',
            field=models.CharField(choices=[('HOTSPOT', 'Hotspot'), ('PPPOE', 'PPPoE'), ('STATIC', 'Static'), ('VPN_PPT', 'VPN (PPTP)'), ('VPN_L2TP', 'VPN (L2TP)'), ('VPN_OVPN', 'VPN (OpenVPN)')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['connection_type'], name='customers_p_connect_d49a97_idx'),
        ),
    ]
