# Generated by Django 5.1.8 on 2025-04-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('hotspot_login_method', models.CharField(choices=[('TRANSACTION', 'M-Pesa Transaction Code'), ('PHONE', 'Phone Number'), ('VOUCHER', 'Voucher Code')], default='TRANSACTION', help_text='Default login method for Hotspot users', max_length=20)),
                ('country', models.CharField(choices=[('KE', 'Kenya (+254)'), ('US', 'United States (+1)'), ('UK', 'United Kingdom (+44)')], default='KE', max_length=2)),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling (KSh)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)')], default='KES', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
