# Generated by Django 5.1.8 on 2025-04-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('hotspot_login_method', models.CharField(choices=[('TRANSACTION', 'M-Pesa Transaction Code'), ('PHONE', 'Phone Number'), ('VOUCHER', 'Voucher Code')], default='TRANSACTION', help_text='Default login method for Hotspot users', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
